  - set_fact:
      pkg_name: "apache2"
    when: ansible_os_family == 'Debian'

  - set_fact:
      pkg_name: "httpd"
    when: ansible_os_family == 'RedHat'

  - set_fact:
      index:
        - Kernel version={{ ansible_kernel_version }}
        - Hostname = {{ ansible_fqdn }}
        - OS = {{ ansible_os_family }}
        - Package = {{ pkg_name }}
        - DATE = {{ ansible_date_time.iso8601 }}

  - shell: cat /etc/os-release|grep 'PRETTY_NAME'|awk -F'=' '{print $2}'| tr -d '"'
    register: os_release_pretty_name_out

  - set_fact:
      index_key_val:
        kernel_version: "{{ ansible_kernel_version }}"
        hostname: "{{ ansible_fqdn }}"
        os: "{{ ansible_os_family }}"
        package: "{{ pkg_name }}"
        date: "{{ ansible_date_time.iso8601 }}"
        pretty_os_name: "{{ os_release_pretty_name_out.stdout }}"
  - package: name="{{ pkg_name }}"
    become: true

  - template: src=index.html.j2 dest=/var/www/html/index2.html
    become: true
  - template: src=index2.html.j2 dest=/var/www/html/index.html
    become: true


  - service:
      name: "{{ pkg_name }}"
      state: started
      enabled: true

  - uri:
      url: http://localhost
      return_content: yes
    register: resp
    failed_when: resp.content is not search("{{ ansible_os_family }}")
